export const SET_MOVIE_HISTORY = 'SET_MOVIE_HISTORY';
export const SET_MOVIE_HISTORY_SUCCESS = 'SET_MOVIE_HISTORY_SUCCESS';
export const SET_MOVIE_HISTORY_FAILURE = 'SET_MOVIE_HISTORY_FAILURE';
export const SET_MOVIE_HISTORY_ERROR = 'SET_MOVIE_HISTORY_ERROR';
export const GET_MOVIE_HISTORY = 'GET_MOVIE_HISTORY';
export const GET_MOVIE_HISTORY_SUCCESS = 'GET_MOVIE_HISTORY_SUCCESS';
export const GET_MOVIE_HISTORY_FAILURE = 'GET_MOVIE_HISTORY_FAILURE';
export const GET_MOVIE_HISTORY_ERROR = 'GET_MOVIE_HISTORY_ERROR';
