export const FETCH_MOVIES_DETAILS = 'FETCH_MOVIES_DETAILS';
export const FETCH_MOVIES_DETAILS_SUCCESS = 'FETCH_MOVIES_DETAILS_SUCCESS';
export const FETCH_MOVIES_DETAILS_ERROR = 'FETCH_MOVIES_DETAILS_ERROR';
